application: bengdict
version: 1
runtime: python
api_version: 1

handlers:
- url: /input
  script: main.py
  login: required

- url: /admin
  script: main.py
  login: admin

- url: .*
  script: main.py
